### ISSUE TITLE
Please add documentation on how to get USER_TOKEN

### ISSUE THREAD

**Issue by smulder** [bhushankumarl/eBay-node-client#10]
I am having trouble wrapping my head around how to get this environment variable "USER_TOKEN" so I can call anything in this library. Any help would me greatly appreciated!

Scott

https://github.com/bhushankumarl/eBay-node-client/blob/8ccf6782554be5d0dcfbb27379418640ecf52bfc/examples/javaScript/utils/index.js#L3

**Comment by bhushankummar** [comment]
@smulder Documentation is available here.
https://developer.ebay.com/api-docs/static/oauth-tokens.html

**Comment by bhushankummar** [comment]
@smulder 
#14 
Support has been extended in the same package. You can find the example here :
https://github.com/bhushankumarl/eBay-node-client/tree/master/examples/javaScript/user
