### ISSUE TITLE
Browse Search

### ISSUE THREAD

**Issue by ineffablep** [bhushankumarl/eBay-node-client#11]
Hi, 
I am using your example but getting below results for search, Please let me know where is it going wrong.

Code: 
`  eBay.application.getOAuthToken({
            grant_type: 'client_credentials',
            scope: 'https://api.ebay.com/oauth/api_scope'
        }).then(token => {
            eBay.setToken(token.access_token);
            eBay.browse.getItem(itemId).then(response => {
                res.send(response);
            }).catch(er => {
                console.log(er);
                res.status(500).send(er);
            });`

**Response**
```
{
"href": "https://api.sandbox.ebay.com/buy/browse/v1/item_summary/search?limit=50&gtin=5011100517&offset=0",
"total": 0,
"limit": 50,
"offset": 0
}
```

**Comment by bhushankummar** [comment]
@ineffablep 
There is nothing wrong in that.
The only possibility is, their no product matched using `gtin=5011100517`.
