### ISSUE TITLE
pagination does not work

### ISSUE THREAD

**Issue by alsguimaraes** [bhushankumarl/eBay-node-client#19]
Calls to eBay.inventory.getInventoryItems({ offset: 25, limit: 25}) do not work.
Ignores all parameters. Apparently library does not set offset and limit anywhere.

**Comment by bhushankummar** [comment]
@alsguimaraes 
Please check this example.
https://github.com/bhushankumarl/eBay-node-client/blob/master/examples/javaScript/sell/inventory/getInventoryItems.js

```
    var data = {
        limit: '10'
    };
    try {
        var response = await eBay.inventory.getInventoryItems(data);
        console.log('response', response);
    } catch (error) {
        console.log('error ', error);
        return;
    }
```
