### ISSUE TITLE
add fulfillment api

### ISSUE THREAD

**Issue by hanselke** [bhushankumarl/eBay-node-client#22]
any plans to support fulfillment? looking for a way to know when sales has happened

**Comment by bhushankummar** [comment]
@hanselke 
Can you point out the documentation?

**Comment by bhushankummar** [comment]
@hanselke 
We'll add support for this API soon.

**Comment by bhushankummar** [comment]
Added in https://github.com/bhushankumarl/eBay-node-client/pull/31

**Comment by bhushankummar** [comment]
It has been released in https://github.com/bhushankumarl/eBay-node-client/releases/tag/v0.0.10 version. Please upgrade your `ebay-node-client` version to the latest.
