### ISSUE TITLE
How can you use searchByImage with eBay-node-client?

### ISSUE THREAD

**Issue by doverradio** [bhushankumarl/eBay-node-client#23]
Ebay is giving [API access on searchbyimage](https://developer.ebay.com/api-docs/buy/browse/resources/search_by_image/methods/searchByImage). Can this be used with your library? I want to search ebay for items with only image.

**Comment by bhushankummar** [comment]
Added in #31

**Comment by bhushankummar** [comment]
It has been released in https://github.com/bhushankumarl/eBay-node-client/releases/tag/v0.0.10 version. Please upgrade your `ebay-node-client` version to the latest.
