### ISSUE TITLE
support for bulkUpdatePriceQuantity

### ISSUE THREAD

**Issue by u007** [bhushankumarl/eBay-node-client#27]
hi,

nice work :)
do you have plans to support this function?
https://developer.ebay.com/api-docs/sell/inventory/resources/inventory_item/methods/bulkUpdatePriceQuantity

**Comment by bhushankummar** [comment]
It has been fixed in #31

**Comment by bhushankummar** [comment]
It has been released in https://github.com/bhushankumarl/eBay-node-client/releases/tag/v0.0.10 version. Please upgrade your `ebay-node-client` version to the latest.
