### ISSUE TITLE
Function bulkCreateOrReplaceInventoryItem

### ISSUE THREAD

**Issue by dlportel** [bhushankumarl/eBay-node-client#28]
Hi, the library has implemented the bulkCreateOrReplaceInventoryItem function from Inventory API?

Nice work... thanks!

**Comment by bhushankummar** [comment]
It has been fixed in #31

**Comment by bhushankummar** [comment]
It has been released in https://github.com/bhushankumarl/eBay-node-client/releases/tag/v0.0.10 version. Please upgrade your `ebay-node-client` version to the latest.

**Comment by dlportel** [comment]
Nice!!!!
